# ビルドステージ
# aplineはバイナリを最小限に抑え、セキュリティ的に堅牢にするため
FROM golang:1.22-alpine as builder

# コンテナ内にどう生成するかの指定
WORKDIR /tmp/grpc-chat

COPY . .

ENV CGO_ENABLE=0

RUN go build -ldflags="-d -s -w" -tags timetzdata -trimpath -o app .

# 実行ステージ

FROM scratch

COPY --from=builder /tmp/grpc-chat/app /app
COPY --from=alpine:latest /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

EXPOSE 6262/tcp

ENTRYPOINT ["/app"]
